### PR TITLE
Add ScalaPB example and update README.md

### PR DESCRIPTION
**Pull request by ikhoon**
- fs2-grpc is not supported at the moment so ScalaPB-Reactor example is added instead.
- Add server and client example to README.md
- Fix Scaladoc error
- Dependencies
  - Armeria 1.3.0 -> 1.4.0
  - fs2 2.4.6 -> 2.5.0
  - http4s 0.21.13 -> 0.21.16

### CODE REVIEW

**Comment by rossabaker** [comment]
Is there a technical problem with fs2-grpc, or just not integrated here?  I'm involved in that project, mostly to hit merge buttons, as I don't do any grpc right now.  But if it's missing something, I can try to facilitate making it happen.

**Comment by ikhoon** [comment]
> Is there a technical problem with fs2-grpc, or just not integrated here?

I guess there is a bug in Armeria gRPC implementation. I have already discussed the bug with other Armeria maintainers and will fix it in the next release of Armeria. 😀

**Comment by ikhoon** [comment]
After merging this PR, I am going to release the first version of http4s-armeria with `0.1.0`.
The next version will be `0.21.6+` which is used in [http4s-finagle](https://http4s.github.io/http4s-finagle/docs/install.html) version scheme when fs2 integration is finished.
Otherwise, users should explicitly specify Armeria version to use fs2-grpc.

**Comment by rossabaker** [comment]
Ping me when it sinks to Maven Central, and I'll tweet it from the http4s account.

**Pull request merged**
